[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

# SPA fallback (prevents 404 on refresh/deep links)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
